version: "3.9"

services:
  frontend-app:
    container_name: covid_fe
    build: ./covid-fe
    restart: always
    volumes:
      - node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD-SHELL", "curl http://0.0.0.0:3000/" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - covid_network
  backend-app:
    container_name: covid-app
    build:
      context: ./covid-be
      dockerfile: docker/Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - "9000:9000"
    healthcheck:
      test: [ "CMD-SHELL", "curl http://0.0.0.0:9000/" ]
      interval: 60s
      timeout: 5s
      retries: 5
    networks:
      - covid_network

  database:
    image: postgis/postgis
    container_name: postgis
    restart: always
    volumes:
        - covid_postgis_data:/var/lib/postgresql/data
        - ./covid-be/postgis/init:/docker-entrypoint-initdb.d
        - ./covid-be/postgis:/home
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=covid
    ports:
        - 5432:5432
    networks:
      - covid_network

networks:
  covid_network:
    name: covid_network
    driver: bridge

volumes:
  node_modules:
  covid_postgis_data: