version: "3.9"

services:
  backend-app:
    container_name: covid-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - "9000:9000"
    healthcheck:
      test: [ "CMD-SHELL", "curl http://0.0.0.0:9000/" ]
      interval: 60s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

  database:
    image: postgis/postgis
    container_name: postgis
    restart: always
    volumes:
        - covid_postgis_data:/var/lib/postgresql/data
        - ./postgis/init:/docker-entrypoint-initdb.d
        - ./postgis:/home
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=covid
    ports:
        - 5433:5432
    networks:
      - backend-network

volumes:
  covid_postgis_data:

networks:
  backend-network:
    name: backend-network
    driver: bridge